on: 
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]
name: ci/github

permissions:
  contents: read

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       go-version: [1.17.x]
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ${{ matrix.go-version }}
  #   - name: Check out code
  #     uses: actions/checkout@v2
  #   - name: Unit Test
  #     run: make test
  #   - name: Integration Test
  #     run: make test-integration
  e2e:
    strategy:
      matrix:
        kubernetes: [v1.21.2]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: ${{ matrix.kubernetes }}
    - name: Install Ko
      # This sha corresponds to v0.4
      uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675
      with:
        version: v0.11.2
    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.11.1
        node_image: kindest/node:${{ matrix.kubernetes }}
        cluster_name: kind
        config: test/e2e/testdata/kind.yaml
        wait: 120s
    - name: Verify kind cluster
      run: |
        echo "# Using KinD context..."
        kubectl config use-context "kind-kind"
        echo "# KinD nodes:"
        kubectl get nodes
        NODE_STATUS=$(kubectl get node kind-control-plane -o json | jq -r .'status.conditions[] | select(.type == "Ready") | .status')
        if [ "${NODE_STATUS}" != "True" ]; then
          echo "# Node is not ready:"
          kubectl describe node kind-control-plane
          echo "# Pods:"
          kubectl get pod -A
          echo "# Events:"
          kubectl get events -A
          exit 1
        fi
    - name: Install Shipwight Build
      run: |
        kubectl apply -f https://github.com/shipwright-io/build/releases/download/v0.9.0/release.yaml
        kubectl apply -f https://github.com/shipwright-io/build/releases/download/v0.9.0/sample-strategies.yaml
    - name: Deploy
      run: make deploy KO=/usr/local/bin/ko IMAGE_REPO=kind.local
    - name: Test
      run: make test-e2e